server:
  host: 0.0.0.0
  port: 3000
db:
  Urls: sqlite:///db.sqlite3
twitter:
  CONSUMER_KEY: xxxxxxxxxxxxxxxxxx
  CONSUMER_SECRET: xxxxxxxxxxxxxxxxxxxx
  ACCESS_TOKEN: xxxxxxxxxxxxxxxx
  ACCESS_SECRET: xxxxxxxxxxxxxxxx
